server:
  port: 8008
  servlet:
    session:
      timeout: 60000

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/losesystem?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: qq123456!
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        #deny: 192.168.1.100
  servlet:
    multipart:
      max-file-size: 20MB
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml
  type-aliases-package: top.zhangdengzhen.demo.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#关闭驼峰
    map-underscore-to-camel-case: false

wx:
  mp:
    appid: wxb225337eb6ca7575
    appSecret: 053a77eb11140bde2af08dc827ae4253
  public:
    appid: wx4b07c85a81baf63f
    appsecret: 6320063d6b511a1f8d49d6028dd07fe2
    template_id: _0_Pa1GRyB_5TmYHu_z3GZvULsXTPP8mrhqFyXCQHl4

ali:
  identify:
    appcode: 3f7545150d3a4d2cb8eced72f9b88b74
    url: https://dfidveri.market.alicloudapi.com/verify_id_name

python:
#  根据网络图片，生成特征值，存到redis
  base_url: http://localhost:8000
  img_url: /setfeatbyurl
  delete_byname: /delebyname
hutool:
  aes:
#    要16位数
    key: 1234567890abcdef
sms:
  ACCESS_KEY_ID: kmYMcuHQAAUBu1LxyDmJH19L6fMnt2Nbaj2tHQ7H4qxsTQsqR


